Сделал переход в страницу дисциплины
kaspian122/ST-front pull request #37
Opened 2020-05-07 17:22 UTC by kaspian122

2020-05-08 06:27 UTC, tchernykhds requested changes

2020-05-08 06:27 UTC, VechniiNewbie commented on src/pages/disciplinesPage/DisciplinesPage.jsx
> +        history.push(`/student-disciplines/${item.id}`);
фигово так называть же? почему не сделать ролевое разделение в одном роуте?

2020-05-08 06:27 UTC, VechniiNewbie commented on src/pages/studentDisciplinePage/StudentDisciplinePage.jsx
> +    setTitle((discipline.discipline && discipline.discipline.name) || 'Дисциплины');
`discipline.discipline`
![image](https://user-images.githubusercontent.com/36907797/81377375-88a18a80-912f-11ea-94df-af4f2398c966.png)

2020-05-08 06:32 UTC, kaspian122 commented on src/pages/disciplinesPage/DisciplinesPage.jsx
> +        history.push(`/student-disciplines/${item.id}`);
А наш роутинг это поддерживает?

2020-05-08 06:32 UTC, kaspian122 commented on src/pages/studentDisciplinePage/StudentDisciplinePage.jsx
> +    setTitle((discipline.discipline && discipline.discipline.name) || 'Дисциплины');
По кайфу же

2020-05-08 06:41 UTC, VechniiNewbie commented on src/pages/disciplinesPage/DisciplinesPage.jsx
> +        history.push(`/student-disciplines/${item.id}`);
в компонент сделать разделение, как я делал для дисциплины например когда new и просто :id

2020-05-08 06:52 UTC, kaspian122 commented on src/pages/disciplinesPage/DisciplinesPage.jsx
> +        history.push(`/student-disciplines/${item.id}`);
Понял про что ты типо `/disciplines/student/:id` или `/student/disciplines/:id`

2020-05-09 16:04 UTC, kaspian122 commented on src/pages/disciplinesPage/DisciplinesPage.jsx
> +        history.push(`/student-disciplines/${item.id}`);
fix

2020-05-09 16:04 UTC, kaspian122 commented on src/pages/studentDisciplinePage/StudentDisciplinePage.jsx
> +    setTitle((discipline.discipline && discipline.discipline.name) || 'Дисциплины');
fix

2020-05-09 16:09 UTC, VechniiNewbie commented on src/pages/disciplinesPage/DisciplinesPage.jsx
> +        history.push(`/student-disciplines/${item.id}`);
Я про то что не важно какая роль, дисциплины это /disciplines/:id

2020-05-19 10:20 UTC, merged